// Language Context - Multilingual Support (English/Kinyarwanda)
import React, { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'My Dashboard',
    'nav.lessons': 'My Lessons',
    'nav.student': 'Student',
    'nav.teacher': 'Teacher',
    'nav.parent': 'Parent',
    'nav.leaderboard': 'Leaderboard',
    'nav.research': 'Research',
    'nav.admin': 'Admin',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.logout': 'Logout',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.games': 'Games',
    'nav.puzzles': 'Puzzles',
    'nav.achievements': 'Achievements',
    'student.games': 'Play Games',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.points': 'points',
    'common.pts': 'pts',
    'common.badges': 'badges',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.refresh': 'Refresh',
    'common.retry': 'Retry',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.select': 'Select',

    // Authentication
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.logout': 'Logout',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.fullName': 'Full Name',
    'auth.role': 'Role',
    'auth.loginSuccess': 'Login successful!',
    'auth.registerSuccess': 'Registration successful!',
    'auth.logoutSuccess': 'Logout successful!',
    'auth.invalidCredentials': 'Invalid email or password',
    'auth.emailRequired': 'Email is required',
    'auth.passwordRequired': 'Password is required',
    'auth.passwordMismatch': 'Passwords do not match',
    'auth.emailInvalid': 'Please enter a valid email address',
    'auth.passwordTooShort': 'Password must be at least 6 characters',
    'auth.userExists': 'User with this email already exists',
    'auth.loginError': 'Login failed. Please try again.',
    'auth.registerError': 'Registration failed. Please try again.',
    'auth.rememberMe': 'Keep me logged in',
    'auth.emailPlaceholder': 'Enter your email address',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.fullNamePlaceholder': 'Enter your full name',
    'auth.confirmPasswordPlaceholder': 'Re-enter your password',
    'auth.emailHint': 'This email will be used for your account',
    'auth.passwordHint': 'At least 6 characters',
    'auth.fullNameRequired': 'Full name is required',
    'auth.teacherSignup': 'TEACHER REGISTRATION',
    'auth.teacherSignupTitle': 'Teacher Sign Up',
    'auth.teacherSignupSubtitle': 'Create your teacher account to start managing students and lessons!',
    'auth.teacherSignupSuccess': 'Congratulations! Your teacher account has been created successfully. You can now manage your students and lessons.',
    'auth.teacherInfo': 'Teacher Information',
    'auth.signUpNow': 'Sign Up Now!',
    'auth.registering': 'Registering...',
    'auth.registrationSuccessful': 'Registration Successful!',
    'auth.redirectingToLogin': 'Redirecting you to the login page...',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.loginRequiredForStudentReg': 'Please login as a teacher to register students',
    'auth.studentNotRegistered': 'Student not registered yet?',
    'auth.registerStudentHere': 'Register the student here',
    'auth.registrationError': 'Registration Error',
    'auth.errorHelpText': 'Please check the information above and try again. If the problem persists, ensure the backend server is running.',
    'auth.accountReadyToLogin': 'Your account is ready! You can now login with the email and password you just created.',

    // Login Type Selection
    'auth.selectLoginType': 'How would you like to login?',
    'auth.selectLoginSubtitle': 'Choose the option that best describes you',
    'auth.teacherLogin': 'Teacher Login',
    'auth.teacherLoginDesc': 'Login with email and password',
    'auth.teacherLoginSubtitle': 'Enter your credentials to access your teacher dashboard',
    'auth.studentLogin': 'Student Login',
    'auth.studentLoginDesc': 'Answer a few simple questions',
    'auth.studentLoginSubtitle': 'We\'ll ask you some questions to help you login safely',

    // Student Login Questions
    'auth.student.question1': 'What is your name?',
    'auth.student.question1Desc': 'Please enter your full name as registered by your teacher',
    'auth.student.question2': 'Which grade are you in?',
    'auth.student.question2Desc': 'Select the grade you are currently studying in',
    'auth.student.question3': 'What is your registration code?',
    'auth.student.question3Desc': 'Enter the 6-character code your teacher gave you',
    'auth.student.namePlaceholder': 'Type your full name here...',
    'auth.student.codePlaceholder': 'ABC123',
    'auth.student.nameRequired': 'Please enter your full name',
    'auth.student.gradeRequired': 'Please select your grade',
    'auth.student.codeRequired': 'Please enter your registration code',
    'auth.student.yourAnswers': 'Your Answers:',
    'auth.student.name': 'Name',
    'auth.student.grade': 'Grade',
    'auth.student.code': 'Registration Code',
    'auth.student.startLearning': 'Start Learning!',

    // Grades
    'grades.grade1': 'Grade 1',
    'grades.grade2': 'Grade 2',
    'grades.grade3': 'Grade 3',
    'grades.grade4': 'Grade 4',
    'grades.grade5': 'Grade 5',
    'grades.grade6': 'Grade 6',

    // Roles
    'role.learner': 'Learner',
    'role.teacher': 'Teacher',
    'role.admin': 'Administrator',
    'role.selectRole': 'Select your role',
    'role.roleDescription.learner': 'I am a student learning digital literacy',
    'role.roleDescription.teacher': 'I am a teacher managing students and lessons',
    'role.roleDescription.admin': 'I am an administrator managing the platform',

    // Student Dashboard
    'student.welcome': 'Welcome back',
    'student.dashboard': 'Student Dashboard',
    'student.progress': 'My Progress',
    'student.lessons': 'My Lessons',
    'student.badges': 'My Badges',
    'student.achievements': 'Achievements',
    'student.level': 'Level',
    'student.points': 'Points',
    'student.streak': 'Day Streak',
    'student.lessonsCompleted': 'Lessons Completed',
    'student.badgesEarned': 'Badges Earned',
    'student.totalPoints': 'Total Points',
    'student.recentActivity': 'Recent Activity',
    'student.continueLearning': 'Continue Learning',
    'student.startLesson': 'Start Lesson',
    'student.resumeLesson': 'Resume Lesson',
    'student.completeLesson': 'Complete Lesson',
    'student.newBadge': 'New Badge Earned!',
    'student.levelUp': 'Level Up!',
    'student.achievementUnlocked': 'Achievement Unlocked!',

    // Teacher Dashboard
    'teacher.dashboard': 'Teacher Dashboard',
    'teacher.classes': 'My Classes',
    'teacher.students': 'My Students',
    'teacher.lessons': 'Lessons',
    'teacher.progress': 'Student Progress',
    'teacher.analytics': 'Analytics',
    'teacher.createClass': 'Create Class',
    'teacher.assignLesson': 'Assign Lesson',
    'teacher.viewProgress': 'View Progress',
    'teacher.manageStudents': 'Manage Students',
    'teacher.classOverview': 'Class Overview',
    'teacher.studentProgress': 'Student Progress',
    'teacher.lessonStats': 'Lesson Statistics',
    'teacher.engagement': 'Engagement Metrics',
    'teacher.registerStudent': 'Register Student',
    'teacher.registerStudentDesc': 'Register new students and manage their registration codes',
    'teacher.registerNewStudent': 'Register New Student',
    'teacher.studentRegisteredSuccess': 'Student Registered Successfully!',
    'teacher.copyToClipboard': 'Copy to clipboard',
    'teacher.shareCodeWithStudent': 'Share this code with the student for login.',
    'teacher.studentFullName': 'Student Full Name',
    'teacher.enterStudentName': 'Enter student\'s full name',
    'teacher.ageOptional': 'Age (optional)',
    'teacher.age': 'Age',
    'teacher.registering': 'Registering...',
    'teacher.registeredStudents': 'Registered Students',
    'teacher.noStudentsYet': 'No students registered yet.',
    'teacher.registerFirstStudent': 'Register your first student using the form above.',
    'teacher.registered': 'Registered',
    'teacher.studentRegFailed': 'Registration failed',
    'teacher.studentRegError': 'Failed to register student. Please try again.',

    // Parent Dashboard
    'parent.dashboard': 'Parent Dashboard',
    'parent.children': 'My Children',
    'parent.progress': 'Child Progress',
    'parent.achievements': 'Child Achievements',
    'parent.activities': 'Recent Activities',
    'parent.overview': 'Overview',
    'parent.detailedProgress': 'Detailed Progress',
    'parent.weeklyReport': 'Weekly Report',
    'parent.monthlyReport': 'Monthly Report',
    'parent.badges': 'Badges Earned',
    'parent.timeSpent': 'Time Spent Learning',
    'parent.lessonsCompleted': 'Lessons Completed',
    'parent.averageScore': 'Average Score',

    // Admin Dashboard
    'admin.dashboard': 'Admin Dashboard',
    'admin.users': 'User Management',
    'admin.classes': 'Class Management',
    'admin.lessons': 'Lesson Management',
    'admin.analytics': 'Platform Analytics',
    'admin.settings': 'System Settings',
    'admin.reports': 'Reports',
    'admin.userStats': 'User Statistics',
    'admin.lessonStats': 'Lesson Statistics',
    'admin.engagementStats': 'Engagement Statistics',
    'admin.systemHealth': 'System Health',
    'admin.dataExport': 'Data Export',
    'admin.backup': 'Backup & Restore',

    // Lessons
    'lesson.title': 'Lesson',
    'lesson.lessons': 'Lessons',
    'lesson.start': 'Start Lesson',
    'lesson.resume': 'Resume Lesson',
    'lesson.complete': 'Complete Lesson',
    'lesson.progress': 'Progress',
    'lesson.score': 'Score',
    'lesson.timeSpent': 'Time Spent',
    'lesson.attempts': 'Attempts',
    'lesson.difficulty': 'Difficulty',
    'lesson.duration': 'Duration',
    'lesson.type': 'Type',
    'lesson.typing': 'Typing',
    'lesson.safety': 'Internet Safety',
    'lesson.coding': 'Coding',
    'lesson.general': 'General',
    'lesson.beginner': 'Beginner',
    'lesson.intermediate': 'Intermediate',
    'lesson.advanced': 'Advanced',
    'lesson.completed': 'Completed',
    'lesson.inProgress': 'In Progress',
    'lesson.notStarted': 'Not Started',
    'lesson.congratulations': 'Congratulations!',
    'lesson.wellDone': 'Well done!',
    'lesson.tryAgain': 'Try Again',
    'lesson.nextLesson': 'Next Lesson',
    'lesson.previousLesson': 'Previous Lesson',

    // Gamification
    'gamification.badges': 'Badges',
    'gamification.achievements': 'Achievements',
    'gamification.leaderboard': 'Leaderboard',
    'gamification.points': 'Points',
    'gamification.level': 'Level',
    'gamification.streak': 'Streak',
    'gamification.rank': 'Rank',
    'gamification.progress': 'Progress',
    'gamification.earned': 'Earned',
    'gamification.available': 'Available',
    'gamification.criteria': 'Criteria',
    'gamification.description': 'Description',
    'gamification.icon': 'Icon',
    'gamification.category': 'Category',
    'gamification.achievement': 'Achievement',
    'gamification.milestone': 'Milestone',
    'gamification.special': 'Special',
    'gamification.weekly': 'Weekly',
    'gamification.monthly': 'Monthly',

    // Errors
    'error.general': 'Something went wrong. Please try again.',
    'error.network': 'Network error. Please check your connection.',
    'error.unauthorized': 'You are not authorized to perform this action.',
    'error.forbidden': 'Access denied.',
    'error.notFound': 'The requested resource was not found.',
    'error.serverError': 'Server error. Please try again later.',
    'error.validation': 'Please check your input and try again.',
    'error.loading': 'Failed to load data. Please try again.',
    'error.saving': 'Failed to save data. Please try again.',
    'error.deleting': 'Failed to delete. Please try again.',
    'error.uploading': 'Failed to upload. Please try again.',
    'error.downloading': 'Failed to download. Please try again.',

    // Success Messages
    'success.saved': 'Data saved successfully!',
    'success.deleted': 'Deleted successfully!',
    'success.uploaded': 'Uploaded successfully!',
    'success.downloaded': 'Downloaded successfully!',
    'success.updated': 'Updated successfully!',
    'success.created': 'Created successfully!',
    'success.completed': 'Completed successfully!',
    'success.achievement': 'Achievement unlocked!',
    'success.badge': 'Badge earned!',
    'success.levelUp': 'Level up!',

    // Accessibility
    'accessibility.highContrast': 'High Contrast',
    'accessibility.largeText': 'Large Text',
    'accessibility.screenReader': 'Screen Reader',
    'accessibility.keyboard': 'Keyboard Navigation',
    'accessibility.audio': 'Audio Descriptions',
    'accessibility.captions': 'Captions',
    'accessibility.zoom': 'Zoom',
    'accessibility.colorBlind': 'Color Blind Support',
    'accessibility.motor': 'Motor Assistance',
    'accessibility.cognitive': 'Cognitive Support',

    // Research Dashboard
    'research.dashboard': 'Research Dashboard',
    'research.analytics': 'Analytics',
    'research.metrics': 'Metrics',
    'research.export': 'Export Data',
    'research.reports': 'Reports',
    'research.insights': 'Insights',
    'research.data': 'Data Collection',
    'research.usage': 'Usage Statistics',
    'research.engagement': 'Engagement Metrics',
    'research.learning': 'Learning Outcomes',
    'research.accessibility': 'Accessibility Usage',
    'research.language': 'Language Preferences',
    'research.connectivity': 'Connectivity Patterns',

    // Welcome Page
    'welcome.title': 'DigLearners',
    'welcome.subtitle': 'Fun Digital Learning for Kids!',
    'welcome.description': 'Learn digital skills through exciting games, puzzles, and activities! Perfect for young learners with colorful lessons and fun challenges.',
    'welcome.enrollChild': 'Register the Student',
    'welcome.login': 'Login',
    'welcome.studentLogin': 'Student Login',
    'welcome.teacherLogin': 'Teacher Login',
    'welcome.whyDigLearners': 'Why Kids Love DigLearners!',
    'welcome.feature1': 'Fun Games & Puzzles',
    'welcome.feature1Desc': 'Learn while playing exciting games, solving puzzles, and completing fun activities!',
    'welcome.feature2': 'Earn Badges & Stars',
    'welcome.feature2Desc': 'Get cool badges and stars when you complete lessons and do great work!',
    'welcome.feature3': 'Learn in Your Language',
    'welcome.feature3Desc': 'Available in English and Kinyarwanda so you can learn in your favorite language!',
    'welcome.feature4': 'Family Fun',
    'welcome.feature4Desc': 'Your parents can see how well you\'re doing and celebrate your achievements!',
    'welcome.feature5': 'Works Everywhere',
    'welcome.feature5Desc': 'Learn at home, at school, or anywhere - even without internet!',
    'welcome.feature6': 'Colorful & Fun',
    'welcome.feature6Desc': 'Beautiful colors and fun characters make learning exciting and enjoyable!',
    'welcome.readyToStart': 'Ready to Start Your Digital Adventure?',
    'welcome.joinThousands': 'Join thousands of kids already having fun while learning digital skills!',
    'welcome.enrollToday': 'Register the Student Today!',
    'welcome.forParents': 'For Teachers:',
    'welcome.parentNote': 'Register your students to help them get started with digital learning!',
    'welcome.chooseLanguage': 'Choose Language',
    'welcome.madeByTeachers': 'MADE BY TEACHERS',
    'welcome.joinTheFun': 'JOIN THE FUN!',
    'welcome.teacherSignUp': 'Teacher, Sign Up for Free',

    // Cat Movement Game
    'game.cat.challenge1.title': '🐱 Help the Cat Find Food!',
    'game.cat.challenge1.description': 'Click blocks to make the cat move to the food bowl 🍽️',
    'game.cat.challenge1.hint': 'Go right twice, then forward (up) twice to reach the food!',
    'game.cat.challenge2.title': '🐱 Cat Adventure!',
    'game.cat.challenge2.description': 'Guide the cat through a fun path! 🎯',
    'game.cat.challenge2.hint': 'Go right three times, then forward once!',
    'game.cat.challenge3.title': '🐱 Final Challenge!',
    'game.cat.challenge3.description': 'Last challenge! Make the cat reach the finish! 🏁',
    'game.cat.challenge3.hint': 'Go right four times, then forward three times!',
    'game.cat.block.forward': 'Move Forward',
    'game.cat.block.backward': 'Move Backward',
    'game.cat.block.left': 'Move Left',
    'game.cat.block.right': 'Move Right',
    'game.cat.blocks.title': 'Click blocks to add them:',
    'game.cat.code.title': 'Your Code:',
    'game.cat.code.empty': 'No blocks selected yet. Click blocks above to add them!',
    'game.cat.actions.run': 'Run Code!',
    'game.cat.actions.reset': 'Reset',
    'game.cat.actions.hint': 'Hint',
    'game.cat.feedback.success': 'Awesome! You did it! Moving to next challenge...',
    'game.cat.feedback.error': 'Not quite right! Try again! The cat needs to reach the food bowl!',
    'game.cat.progress': 'Challenge {current} of {total} | Score: {score}',

    // Puzzles
    'puzzle.grade1.q1.question': 'What shape is this? ⭕',
    'puzzle.grade1.q1.answer': 'Circle',
    'puzzle.grade1.q1.option1': 'Circle',
    'puzzle.grade1.q1.option2': 'Square',
    'puzzle.grade1.q1.option3': 'Triangle',
    'puzzle.grade1.q1.option4': 'Rectangle',
    'puzzle.grade1.q2.question': 'What color is this? 🔴',
    'puzzle.grade1.q2.answer': 'Red',
    'puzzle.grade1.q2.option1': 'Red',
    'puzzle.grade1.q2.option2': 'Blue',
    'puzzle.grade1.q2.option3': 'Green',
    'puzzle.grade1.q2.option4': 'Yellow',
    'puzzle.grade1.q3.question': 'Count the stars: ⭐⭐⭐',
    'puzzle.grade1.q3.answer': '3',
    'puzzle.grade1.q3.option1': '1',
    'puzzle.grade1.q3.option2': '2',
    'puzzle.grade1.q3.option3': '3',
    'puzzle.grade1.q3.option4': '4',
    'puzzle.grade4.q1.question': 'What is 1/2 of 8?',
    'puzzle.grade4.q1.answer': '4',
    'puzzle.grade4.q1.option1': '2',
    'puzzle.grade4.q1.option2': '3',
    'puzzle.grade4.q1.option3': '4',
    'puzzle.grade4.q1.option4': '5',
    'puzzle.grade4.q2.question': 'Which is a noun?',
    'puzzle.grade4.q2.answer': 'book',
    'puzzle.grade4.q2.option1': 'run',
    'puzzle.grade4.q2.option2': 'happy',
    'puzzle.grade4.q2.option3': 'book',
    'puzzle.grade4.q2.option4': 'quickly',
    'puzzle.grade4.q3.question': '12 ÷ 3 = ?',
    'puzzle.grade4.q3.answer': '4',
    'puzzle.grade4.q3.option1': '3',
    'puzzle.grade4.q3.option2': '4',
    'puzzle.grade4.q3.option3': '5',
    'puzzle.grade4.q3.option4': '6',
    'puzzle.feedback.correct': 'Correct! Well done!',
    'puzzle.progress': 'Puzzle {current} of {total}',

    // Story Game
    'story.page1.text': "Hi! I'm Whiskers the Cat! 🐱 Meow meow! Let's go on an amazing digital adventure together!",
    'story.page2.text': "Look! I found a super cool computer! 💻 Let me show you how it works! Click Next to see me explore!",
    'story.page3.text': "Wow! I'm typing on the keyboard! ⌨️ Watch me go! Tap tap tap! This is so fun! Want to try?",
    'story.page4.text': "Yay! I'm surfing the internet safely! 🌐 Always remember to be safe online, just like me! Ask grown-ups for help!",
    'story.page5.text': "Hooray! We did it! 🎉 I'm now a digital expert cat! Thanks for learning with me! You're awesome! 🌟",
    'story.button.next': 'Next Page → 🎮',
    'story.button.finish': 'Finish Story! 🎉',
    'story.progress': 'Page {current} of {total}',

    // Default Game
    'game.default.step1': "Hi! I'm Whiskers! 🐱 Let's learn about {subject}! Click Next to start!",
    'game.default.step2': 'Awesome! {subject} is super cool! Watch me explore! 🚀',
    'game.default.step3': 'Wow! Look at all the cool things we can do! This is amazing! ✨',
    'game.default.step4': "You're doing great! Keep going! We're almost done! 💪",
    'game.default.step5': "Hooray! We finished! You're awesome! Thanks for learning with me! 🎉",
    'game.default.subject.default': 'something fun',
    'game.default.button.next': 'Next Step → 🎮',
    'game.default.button.finish': 'Finish! 🎉',
    'game.default.progress': 'Step {current} of {total}'
  },
  rw: {
    // Navigation
    'nav.home': 'Akarubaho Kanjye',
    'nav.lessons': 'Amasomo Yanjye',
    'nav.student': 'Umunyeshuri',
    'nav.teacher': 'Umwarimu',
    'nav.parent': 'Umubyeyi',
    'nav.leaderboard': 'Urutonde',
    'nav.research': 'Ubushakashatsi',
    'nav.admin': 'Umuyobozi',
    'nav.login': 'Winjira',
    'nav.register': 'Iyandikishe',
    'nav.logout': 'Sohoka',
    'nav.profile': 'Umwirondoro',
    'nav.settings': 'Igenamiterere',
    'nav.games': 'Imikino',
    'nav.puzzles': 'Amasomo',
    'nav.achievements': 'Intsinzi',
    'student.games': 'Kina Imikino',

    // Common
    'common.loading': 'Birakora...',
    'common.error': 'Ikosa',
    'common.success': 'Byakunze',
    'common.points': 'amanota',
    'common.pts': 'amanota',
    'common.badges': 'ibimenyetso',
    'common.back': 'Subira inyuma',
    'common.next': 'Ikurikira',
    'common.previous': 'Ibanjirije',
    'common.save': 'Bika',
    'common.cancel': 'Hagarika',
    'common.delete': 'Siba',
    'common.edit': 'Hindura',
    'common.add': 'Ongeraho',
    'common.search': 'Shakisha',
    'common.filter': 'Suzuma',
    'common.sort': 'Gena',
    'common.refresh': 'Ongera ugerageze',
    'common.retry': 'Ongera ugerageze',
    'common.close': 'Funga',
    'common.confirm': 'Emeza',
    'common.yes': 'Yego',
    'common.no': 'Oya',
    'common.select': 'Hitamo',

    // Authentication
    'auth.login': 'Winjira',
    'auth.register': 'Iyandikishe',
    'auth.logout': 'Sohoka',
    'auth.email': 'Imeli',
    'auth.password': 'Ijambo ry\'ibanga',
    'auth.confirmPassword': 'Emeza ijambo ry\'ibanga',
    'auth.fullName': 'Amazina yose',
    'auth.role': 'Uruhare',
    'auth.loginSuccess': 'Winjiye neza!',
    'auth.registerSuccess': 'Wiyandikishije neza!',
    'auth.logoutSuccess': 'Wasohotse neza!',
    'auth.invalidCredentials': 'Imeli cyangwa ijambo ry\'ibanga si byiza',
    'auth.emailRequired': 'Imeli ni ngombwa',
    'auth.passwordRequired': 'Ijambo ry\'ibanga ni ngombwa',
    'auth.passwordMismatch': 'Amajambo y\'ibanga atari kimwe',
    'auth.emailInvalid': 'Shyiramo imeli y\'ukuri',
    'auth.passwordTooShort': 'Ijambo ry\'ibanga rigomba kuba rigira uburebure buhagije',
    'auth.userExists': 'Umukoresha w\'iyi imeli yarimo',
    'auth.loginError': 'Kwinjira byanze. Ongera ugerageze.',
    'auth.registerError': 'Kwiyandikisha byanze. Ongera ugerageze.',
    'auth.rememberMe': 'Nyibuke',
    'auth.emailPlaceholder': 'Shyiramo imeli yawe',
    'auth.passwordPlaceholder': 'Shyiramo ijambo ryawe ryibanga',
    'auth.fullNamePlaceholder': 'Shyiramo amazina yawe yose',
    'auth.confirmPasswordPlaceholder': 'Shyiramo ijambo ry\'ibanga nakomeje',
    'auth.emailHint': 'Iyi imeli izakoreshwa kugira ngo ukoreshe konti yawe',
    'auth.passwordHint': 'Bikwiye kuba bigira uburebure buhagije',
    'auth.fullNameRequired': 'Amazina yose ni ngombwa',
    'auth.teacherSignup': 'KWANDIKISHA UMWARIMU',
    'auth.teacherSignupTitle': 'Kwiyandikisha kw\'Umwarimu',
    'auth.teacherSignupSubtitle': 'Kora konti yawe y\'umwarimu kugira ngo utangire gukurikirana abanyeshuri n\'amasomo!',
    'auth.teacherSignupSuccess': 'Urakoze! Konti yawe y\'umwarimu yakozwe neza. Ubu ushobora gukurikirana abanyeshuri bawe n\'amasomo.',
    'auth.teacherInfo': 'Amakuru y\'Umwarimu',
    'auth.signUpNow': 'Kwiyandikisha Ubu!',
    'auth.registering': 'Birakora...',
    'auth.registrationSuccessful': 'Kwiyandikisha Byakunze!',
    'auth.redirectingToLogin': 'Dukuyobora ku hantu winjira...',
    'auth.alreadyHaveAccount': 'Wagifite konti?',
    'auth.loginRequiredForStudentReg': 'Nyamuneka winjire nk\'umwarimu kugira ngo wandikishe abanyeshuri',
    'auth.studentNotRegistered': 'Umunyeshuri atarandikishijwe?',
    'auth.registerStudentHere': 'Kwandikisha umunyeshuri hano',
    'auth.registrationError': 'Ikosa ry\'Kwiyandikisha',
    'auth.errorHelpText': 'Nyamuneka reba amakuru hejuru hanyuma ongere ugerageze. Niba ikibazo gihagaze, menya ko seriveri ikora neza.',
    'auth.accountReadyToLogin': 'Konti yawe yiteguye! Ubu ushobora kwinjira ukoresheje imeli n\'ijambo ry\'ibanga wagukoreye.',

    // Login Type Selection
    'auth.selectLoginType': 'Ese wishaka kwinjira gute?',
    'auth.selectLoginSubtitle': 'Hitamo icyo gikwiriye',
    'auth.teacherLogin': 'Kwinjira kw\'Umwarimu',
    'auth.teacherLoginDesc': 'Injira ukoresheje imeli n\'ijambo ry\'ibanga',
    'auth.teacherLoginSubtitle': 'Shyiramo amakuru yawe kugira ngo ubone ikibaho cyawe cy\'umwarimu',
    'auth.studentLogin': 'Kwinjira kw\'Umunyeshuri',
    'auth.studentLoginDesc': 'Subiza ibibazo byoroshye',
    'auth.studentLoginSubtitle': 'Tuzakubaza ibibazo kugira ngo winjire neza',

    // Student Login Questions
    'auth.student.question1': 'Witwa nde?',
    'auth.student.question1Desc': 'Nyamuneka shyiramo amazina yawe yose nkuko umwarimu yaguandikishije',
    'auth.student.question2': 'Uri mu rwego ki?',
    'auth.student.question2Desc': 'Hitamo urwego urimo ubu',
    'auth.student.question3': 'Kode yawe y\'iyandikisha ni iyihe?',
    'auth.student.question3Desc': 'Shyiramo kode y\'inyuguti 6 umwarimu yakuhaye',
    'auth.student.namePlaceholder': 'Andika amazina yawe yose hano...',
    'auth.student.codePlaceholder': 'ABC123',
    'auth.student.nameRequired': 'Nyamuneka shyiramo amazina yawe yose',
    'auth.student.gradeRequired': 'Nyamuneka hitamo urwego rwawe',
    'auth.student.codeRequired': 'Nyamuneka shyiramo kode yawe y\'iyandikisha',
    'auth.student.yourAnswers': 'Ibisubizo byawe:',
    'auth.student.name': 'Izina',
    'auth.student.grade': 'Urwego',
    'auth.student.code': 'Kode y\'Iyandikisha',
    'auth.student.startLearning': 'Tangira Kwiga!',

    // Grades
    'grades.grade1': 'Urwego rwa 1',
    'grades.grade2': 'Urwego rwa 2',
    'grades.grade3': 'Urwego rwa 3',
    'grades.grade4': 'Urwego rwa 4',
    'grades.grade5': 'Urwego rwa 5',
    'grades.grade6': 'Urwego rwa 6',

    // Roles
    'role.learner': 'Umunyeshuri',
    'role.teacher': 'Umwarimu',
    'role.admin': 'Umuyobozi',
    'role.selectRole': 'Hitamo uruhare rwawe',
    'role.roleDescription.learner': 'Ndi umunyeshuri wiga ubumenyi bwa digital',
    'role.roleDescription.teacher': 'Ndi umwarimu wita ku banyeshuri n\'amasomo',
    'role.roleDescription.admin': 'Ndi umuyobozi wita ku sisiteme',

    // Student Dashboard
    'student.welcome': 'Murakaza neza',
    'student.dashboard': 'Ikibaho cy\'Umunyeshuri',
    'student.progress': 'Intambwe yanjye',
    'student.lessons': 'Amasomo yanjye',
    'student.badges': 'Ibimenyetso byanjye',
    'student.achievements': 'Intsinzi',
    'student.level': 'Urwego',
    'student.points': 'Amanota',
    'student.streak': 'Iminsi Ikurikirana',
    'student.lessonsCompleted': 'Amasomo Yarangiye',
    'student.badgesEarned': 'Ibimenyetso Mwabonye',
    'student.totalPoints': 'Amanota Yose',
    'student.recentActivity': 'Ibikorwa Biheruka',
    'student.continueLearning': 'Komeza Kwiga',
    'student.startLesson': 'Tangira Isomo',
    'student.resumeLesson': 'Komeza Isomo',
    'student.completeLesson': 'Rangiza Isomo',
    'student.newBadge': 'Ikimenyetso Gishya Mwabonye!',
    'student.levelUp': 'Wazamutse!',
    'student.achievementUnlocked': 'Intsinzi Ryasohoye!',

    // Teacher Dashboard
    'teacher.dashboard': 'Ikibaho cy\'Umwarimu',
    'teacher.classes': 'Amashuri yanjye',
    'teacher.students': 'Abanyeshuri banjye',
    'teacher.lessons': 'Amasomo',
    'teacher.progress': 'Intambwe y\'Abanyeshuri',
    'teacher.analytics': 'Ibisobanuro',
    'teacher.createClass': 'Kora Isomo',
    'teacher.assignLesson': 'Tanga Isomo',
    'teacher.viewProgress': 'Reba Intambwe',
    'teacher.manageStudents': 'Genzura Abanyeshuri',
    'teacher.classOverview': 'Incamake y\'Isomo',
    'teacher.studentProgress': 'Intambwe y\'Umunyeshuri',
    'teacher.lessonStats': 'Ibisobanuro by\'Isomo',
    'teacher.engagement': 'Ibisobanuro by\'Ubufatanye',
    'teacher.registerStudent': 'Kwandikisha Umunyeshuri',
    'teacher.registerStudentDesc': 'Kwandikisha abanyeshuri bashya kandi ukurikirane amakode yabo y\'iyandikisha',
    'teacher.registerNewStudent': 'Kwandikisha Umunyeshuri Mushya',
    'teacher.studentRegisteredSuccess': 'Umunyeshuri Wandikishijwe Neza!',
    'teacher.copyToClipboard': 'Koporora kuri clipboard',
    'teacher.shareCodeWithStudent': 'Kugira ngo umunyeshuri winjire, mugere kode hano.',
    'teacher.studentFullName': 'Amazina Yose y\'Umunyeshuri',
    'teacher.enterStudentName': 'Shyiramo amazina yose y\'umunyeshuri',
    'teacher.ageOptional': 'Iminsi (birashoboka)',
    'teacher.age': 'Iminsi',
    'teacher.registering': 'Birakora...',
    'teacher.registeredStudents': 'Abanyeshuri Bandikishijwe',
    'teacher.noStudentsYet': 'Nta banyeshuri bandikishijwe.',
    'teacher.registerFirstStudent': 'Kwandikisha umunyeshuri wawe wa mbere ukoresheje ifishi hejuru.',
    'teacher.registered': 'Wandikishijwe',
    'teacher.studentRegFailed': 'Kwiyandikisha byanze',
    'teacher.studentRegError': 'Ntabwo byashobotse kwandikisha umunyeshuri. Ongera ugerageze.',

    // Parent Dashboard
    'parent.dashboard': 'Ikibaho cy\'Umubyeyi',
    'parent.children': 'Abana banjye',
    'parent.progress': 'Intambwe y\'Umwana',
    'parent.achievements': 'Intsinzi z\'Umwana',
    'parent.activities': 'Ibikorwa Biheruka',
    'parent.overview': 'Incamake',
    'parent.detailedProgress': 'Intambwe y\'Uruhare',
    'parent.weeklyReport': 'Raporo y\'Icyumweru',
    'parent.monthlyReport': 'Raporo y\'Ukwezi',
    'parent.badges': 'Ibimenyetso Byabonye',
    'parent.timeSpent': 'Igihe Cyakoreshejwe',
    'parent.lessonsCompleted': 'Amasomo Yarangiye',
    'parent.averageScore': 'Amanota y\'Ubwigenge',

    // Admin Dashboard
    'admin.dashboard': 'Ikibaho cy\'Umuyobozi',
    'admin.users': 'Genzura Abakoresha',
    'admin.classes': 'Genzura Amashuri',
    'admin.lessons': 'Genzura Amasomo',
    'admin.analytics': 'Ibisobanuro by\'Ubwoba',
    'admin.settings': 'Igenamiterere',
    'admin.reports': 'Raporo',
    'admin.userStats': 'Ibisobanuro by\'Abakoresha',
    'admin.lessonStats': 'Ibisobanuro by\'Amasomo',
    'admin.engagementStats': 'Ibisobanuro by\'Ubufatanye',
    'admin.systemHealth': 'Ubuzima bwa Sisiteme',
    'admin.dataExport': 'Kuramo Amakuru',
    'admin.backup': 'Gukingira no Kugarura',

    // Lessons
    'lesson.title': 'Isomo',
    'lesson.lessons': 'Amasomo',
    'lesson.start': 'Tangira Isomo',
    'lesson.resume': 'Komeza Isomo',
    'lesson.complete': 'Rangiza Isomo',
    'lesson.progress': 'Intambwe',
    'lesson.score': 'Amanota',
    'lesson.timeSpent': 'Igihe Cyakoreshejwe',
    'lesson.attempts': 'Igerageza',
    'lesson.difficulty': 'Ubukomeye',
    'lesson.duration': 'Igihe',
    'lesson.type': 'Ubwoko',
    'lesson.typing': 'Kwandika',
    'lesson.safety': 'Kurinda mu Internet',
    'lesson.coding': 'Gukora Code',
    'lesson.general': 'Ubwoba',
    'lesson.beginner': 'Umutangizi',
    'lesson.intermediate': 'Uruhare',
    'lesson.advanced': 'Uruhare rwo hejuru',
    'lesson.completed': 'Byarangiye',
    'lesson.inProgress': 'Birakora',
    'lesson.notStarted': 'Ntibyatangijwe',
    'lesson.congratulations': 'Urakoze!',
    'lesson.wellDone': 'Byakunze!',
    'lesson.tryAgain': 'Ongera ugerageze',
    'lesson.nextLesson': 'Isomo Rikurikira',
    'lesson.previousLesson': 'Isomo Ryabanjirije',

    // Gamification
    'gamification.badges': 'Ibimenyetso',
    'gamification.achievements': 'Intsinzi',
    'gamification.leaderboard': 'Urutonde',
    'gamification.points': 'Amanota',
    'gamification.level': 'Urwego',
    'gamification.streak': 'Ikurikirana',
    'gamification.rank': 'Urwego',
    'gamification.progress': 'Intambwe',
    'gamification.earned': 'Byabonye',
    'gamification.available': 'Birahari',
    'gamification.criteria': 'Ibyifuzo',
    'gamification.description': 'Ibisobanuro',
    'gamification.icon': 'Ikimenyetso',
    'gamification.category': 'Icyiciro',
    'gamification.achievement': 'Intsinzi',
    'gamification.milestone': 'Intambwe',
    'gamification.special': 'Byihariye',
    'gamification.weekly': 'Icyumweru',
    'gamification.monthly': 'Ukwezi',

    // Errors
    'error.general': 'Ikintu kirakomeje. Ongera ugerageze.',
    'error.network': 'Ikosa ry\'uruganda. Reba ko uruganda rwawe rukora neza.',
    'error.unauthorized': 'Nta bushobozi bwo gukora iki gikorwa.',
    'error.forbidden': 'Nta bushobozi bwo kwinjira.',
    'error.notFound': 'Icyo ushakaga ntabwo cyabonetse.',
    'error.serverError': 'Ikosa ry\'seriveri. Ongera ugerageze nyuma.',
    'error.validation': 'Reba ko wakoze neza kandi ongera ugerageze.',
    'error.loading': 'Ntabwo byashobotse gutegura amakuru. Ongera ugerageze.',
    'error.saving': 'Ntabwo byashobotse kubika amakuru. Ongera ugerageze.',
    'error.deleting': 'Ntabwo byashobotse gusiba. Ongera ugerageze.',
    'error.uploading': 'Ntabwo byashobotse kwinjiza. Ongera ugerageze.',
    'error.downloading': 'Ntabwo byashobotse kumanura. Ongera ugerageze.',

    // Success Messages
    'success.saved': 'Amakuru yabikijwe neza!',
    'success.deleted': 'Yasibwe neza!',
    'success.uploaded': 'Yinjiye neza!',
    'success.downloaded': 'Yamanuwe neza!',
    'success.updated': 'Yahinduwe neza!',
    'success.created': 'Yakozwe neza!',
    'success.completed': 'Byarangiye neza!',
    'success.achievement': 'Intsinzi ryasohoye!',
    'success.badge': 'Ikimenyetso cyabonye!',
    'success.levelUp': 'Wazamutse!',

    // Accessibility
    'accessibility.highContrast': 'Gutandukanya ibara',
    'accessibility.largeText': 'Inyandiko Nini',
    'accessibility.screenReader': 'Soma Inyandiko',
    'accessibility.keyboard': 'Gukoresha Urufunguzo',
    'accessibility.audio': 'Ibisobanuro by\'Ijwi',
    'accessibility.captions': 'Ibisobanuro',
    'accessibility.zoom': 'Kongera',
    'accessibility.colorBlind': 'Gufasha Abantu batabona ibara',
    'accessibility.motor': 'Gufasha Abantu batagira ubushobozi',
    'accessibility.cognitive': 'Gufasha Ubwoba',

    // Research Dashboard
    'research.dashboard': 'Ikibaho cy\'Ubushakashatsi',
    'research.analytics': 'Ibisobanuro',
    'research.metrics': 'Ibisobanuro',
    'research.export': 'Kuramo Amakuru',
    'research.reports': 'Raporo',
    'research.insights': 'Ibisobanuro',
    'research.data': 'Gukusanya Amakuru',
    'research.usage': 'Ibisobanuro by\'Ukoresha',
    'research.engagement': 'Ibisobanuro by\'Ubufatanye',
    'research.learning': 'Ibyo Wize',
    'research.accessibility': 'Ukoresha Ibyo Bifasha',
    'research.language': 'Ibyifuzo by\'Ururimi',
    'research.connectivity': 'Ibisobanuro by\'Uruganda',

    // Welcome Page
    'welcome.title': 'DigLearners',
    'welcome.subtitle': 'Kwiga neza amasomo y\'ikoranabuhanga',
    'welcome.description': 'Menyekanisha ubumenyi bwa digital ukoresheje imikino myiza, ibisubizo, n\'ibikorwa by\'ubwoba! Byiza ku banyeshuri bato bafite amasomo y\'amabara n\'ibigerageza by\'ubwoba.',
    'welcome.enrollChild': 'Kwandikisha umunyeshuli',
    'welcome.login': 'Injira',
    'welcome.studentLogin': 'Kwinjira kw\'Umunyeshuri',
    'welcome.teacherLogin': 'Kwinjira kw\'Umwarimu',
    'welcome.whyDigLearners': 'Kuki Abana Bakunda DigLearners!',
    'welcome.feature1': 'Imikino myiza n\'Ibisubizo',
    'welcome.feature1Desc': 'Menyekanisha ukina imikino myiza, ukemura ibisubizo, kandi ukangurira ibikorwa by\'ubwoba!',
    'welcome.feature2': 'Bona Ibimenyetso n\'Inyenyeri',
    'welcome.feature2Desc': 'Bona ibimenyetso byiza n\'inyenyeri mugihe wangije amasomo kandi ukora neza!',
    'welcome.feature3': 'Menyekanisha mu Rurimi rwawe',
    'welcome.feature3Desc': 'Birahari mu Cyongereza na Kinyarwanda kugira ngo wige mu rurimi ukunda!',
    'welcome.feature4': 'Ubwoba bw\'Umuryango',
    'welcome.feature4Desc': 'Ababyeyi bawe bashobora kubona uko ukora neza kandi bakagira intsinzi zawe!',
    'welcome.feature5': 'Bikora Ahantu Hose',
    'welcome.feature5Desc': 'Menyekanisha mu rugo, mu ishuri, cyangwa ahantu hose - na nta internet!',
    'welcome.feature6': 'Amabara n\'Ubwoba',
    'welcome.feature6Desc': 'Amabara meza n\'abantu b\'ubwoba bikora kwiga byishimishije kandi byishimishije!',
    'welcome.readyToStart': 'Witeguye Gutangira Ubwoba bwawe bwa Digital?',
    'welcome.joinThousands': 'Jya ku bana benshi bamaze kwishimira kwiga ubumenyi bwa digital!',
    'welcome.enrollToday': 'Kwandikisha umunyeshuli uyu munsi!',
    'welcome.forParents': 'Ku Barimu:',
    'welcome.parentNote': 'Kwandikisha abanyeshuli bawe kugira ngo bagire icyo bakanga gutangira kwiga digital!',
    'welcome.chooseLanguage': 'Hitamo Ururimi',
    'welcome.madeByTeachers': 'Byakozwe n\'abarimu',
    'welcome.joinTheFun': 'JYA KU BWUBA!',
    'welcome.teacherSignUp': 'Umwarimu, Iyandikishe ku Buntu',

    // Cat Movement Game - Kinyarwanda
    'game.cat.challenge1.title': '🐱 Nyamuneka Nyampinga Abone Ibyokurya!',
    'game.cat.challenge1.description': 'Kanda amaboko kugira ngo nyampinga yinyuze kugera ku byokurya 🍽️',
    'game.cat.challenge1.hint': 'Jya iburyo kabiri, hanyuma uze hejuru kabiri kugira ngo ubone ibyokurya!',
    'game.cat.challenge2.title': '🐱 Inzira ya Nyampinga!',
    'game.cat.challenge2.description': 'Yobora nyampinga mu nzira ishimishije! 🎯',
    'game.cat.challenge2.hint': 'Jya iburyo gatatu, hanyuma uze hejuru rimwe!',
    'game.cat.challenge3.title': '🐱 Intsinzi ya Nyuma!',
    'game.cat.challenge3.description': 'Intsinzi ya nyuma! Nyamuneka nyampinga agere ku ntego! 🏁',
    'game.cat.challenge3.hint': 'Jya iburyo kane, hanyuma uze hejuru gatatu!',
    'game.cat.block.forward': 'Ijya Imbere',
    'game.cat.block.backward': 'Subira Inyuma',
    'game.cat.block.left': 'Ijya Iburasirazuba',
    'game.cat.block.right': 'Ijya Iburengerazuba',
    'game.cat.blocks.title': 'Kanda amaboko kugira ngo uyongereho:',
    'game.cat.code.title': 'Kode yawe:',
    'game.cat.code.empty': 'Nta maboko yatoranyijwe. Kanda amaboko hejuru kugira ngo uyongereho!',
    'game.cat.actions.run': 'Genzura Kode!',
    'game.cat.actions.reset': 'Ongera Utangire',
    'game.cat.actions.hint': 'Inkuru',
    'game.cat.feedback.success': 'Byiza! Wabikoreye! Tujya ku ntsinzi ikurikira...',
    'game.cat.feedback.error': 'Ntibyuzuye! Ongera ugerageze! Nyampinga agomba kugera ku byokurya!',
    'game.cat.progress': 'Intsinzi {current} mu {total} | Inyandiko: {score}',

    // Puzzles - Kinyarwanda
    'puzzle.grade1.q1.question': 'Ni ikipi ishusho? ⭕',
    'puzzle.grade1.q1.answer': 'Umuzenguruko',
    'puzzle.grade1.q1.option1': 'Umuzenguruko',
    'puzzle.grade1.q1.option2': 'Umurongo',
    'puzzle.grade1.q1.option3': 'Inyegamo',
    'puzzle.grade1.q1.option4': 'Ikigere',
    'puzzle.grade1.q2.question': 'Ni irihe ibara? 🔴',
    'puzzle.grade1.q2.answer': 'Umutukura',
    'puzzle.grade1.q2.option1': 'Umutukura',
    'puzzle.grade1.q2.option2': 'Ubururu',
    'puzzle.grade1.q2.option3': 'Icyatsi',
    'puzzle.grade1.q2.option4': 'Umuhondo',
    'puzzle.grade1.q3.question': 'Bara inyenyeri: ⭐⭐⭐',
    'puzzle.grade1.q3.answer': '3',
    'puzzle.grade1.q3.option1': '1',
    'puzzle.grade1.q3.option2': '2',
    'puzzle.grade1.q3.option3': '3',
    'puzzle.grade1.q3.option4': '4',
    'puzzle.grade4.q1.question': 'Ni iki 1/2 ya 8?',
    'puzzle.grade4.q1.answer': '4',
    'puzzle.grade4.q1.option1': '2',
    'puzzle.grade4.q1.option2': '3',
    'puzzle.grade4.q1.option3': '4',
    'puzzle.grade4.q1.option4': '5',
    'puzzle.grade4.q2.question': 'Ni iki gisa n\'izina?',
    'puzzle.grade4.q2.answer': 'igitabo',
    'puzzle.grade4.q2.option1': 'kwiruka',
    'puzzle.grade4.q2.option2': 'kwishima',
    'puzzle.grade4.q2.option3': 'igitabo',
    'puzzle.grade4.q2.option4': 'vuba',
    'puzzle.grade4.q3.question': '12 ÷ 3 = ?',
    'puzzle.grade4.q3.answer': '4',
    'puzzle.grade4.q3.option1': '3',
    'puzzle.grade4.q3.option2': '4',
    'puzzle.grade4.q3.option3': '5',
    'puzzle.grade4.q3.option4': '6',
    'puzzle.feedback.correct': 'Byakunze! Wakoze neza!',
    'puzzle.progress': 'Ikiganiro {current} mu {total}',

    // Story Game - Kinyarwanda
    'story.page1.text': 'Muraho! Ndi Nyampinga! 🐱 Meow meow! Reka tugiye mu mukino w\'ubwoba bwa digital hamwe!',
    'story.page2.text': 'Reba! Nshanze mudasobwa nziza! 💻 Reka nkwereke uko ikora! Kanda "Ibikurikira" kugira ngo unyereke uko ndushakisha!',
    'story.page3.text': 'Wow! Ndishyiramo mu kibaho! ⌨️ Reba uko ndakora! Tap tap tap! Bishimishije! Wishaka kugerageza?',
    'story.page4.text': 'Yay! Nshakisha mu isanganya nkagira ubwoba! 🌐 Wibuke wihangane mu isanganya, nk\'uko nakoze! Saba abakuru batugufashe!',
    'story.page5.text': 'Hooray! Twabikoreye! 🎉 Ubu nshinze umuhanga wa digital! Murakoze kwiga hamwe! Wuri nziza! 🌟',
    'story.button.next': 'Ipaji Ikurikira → 🎮',
    'story.button.finish': 'Gusohoza Inkuru! 🎉',
    'story.progress': 'Ipaji {current} mu {total}',

    // Default Game - Kinyarwanda
    'game.default.step1': 'Muraho! Ndi Nyampinga! 🐱 Reka twige kuri {subject}! Kanda "Ibikurikira" gutangira!',
    'game.default.step2': 'Byiza! {subject} birarushaho kuba byiza! Reba uko ndushakisha! 🚀',
    'game.default.step3': 'Wow! Reba ibintu byose dushobora gukora! Birabaho! ✨',
    'game.default.step4': 'Wakoze neza! Komeza! Twageze hafi y\'inyuma! 💪',
    'game.default.step5': 'Hooray! Twarangije! Wuri nziza! Murakoze kwiga hamwe! 🎉',
    'game.default.subject.default': 'ikintu gishimishije',
    'game.default.button.next': 'Intambwe Ikurikira → 🎮',
    'game.default.button.finish': 'Gusohoza! 🎉',
    'game.default.progress': 'Intambwe {current} mu {total}'
  }
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('diglearners-language') || 'en'
  })

  useEffect(() => {
    localStorage.setItem('diglearners-language', language)
  }, [language])

  const t = (key, params = {}) => {
    let translation = translations[language]?.[key] || key
    
    // Replace parameters in translation
    Object.keys(params).forEach(param => {
      translation = translation.replace(`{${param}}`, params[param])
    })
    
    return translation
  }

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage)
  }

  const value = {
    language,
    t,
    changeLanguage,
    availableLanguages: [
      { code: 'en', name: 'English', flag: '🇺🇸' },
      { code: 'rw', name: 'Kinyarwanda', flag: '🇷🇼' }
    ]
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}
